# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy
  - frontendbuild
  - docsdeploy

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - cd backend/sts-workspace/backend
    - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - cd backend/sts-workspace/backend
    - mvn test
  artifacts:
    paths:
      - backend/sts-workspace/backend/target/*.jar
      
# Below stage builds, deploys and executes the jar as service.
# Make sure there is /target directory in your server, else script will fail, or use any other folder you like.
# If you are changing the folder, reflect the change in systemd-web-demo service too.
autoDeploy:
  stage: autodeploy
  tags:
   - shell
  script:
    - cd backend/sts-workspace/backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop systemd-web-demo
    - sudo systemctl start systemd-web-demo
  only:
    - master
    
frontend-build: 
    stage: frontendbuild
    tags:
        - frontend
    script:
        - cd frontend/isu-cytes
        - yarn install
        - CI=false 
        - yarn build
        - sudo cp -r build/* /var/www/html
    only:
      - master

docsDeploy:
  stage: docsdeploy
  tags:
    - shell
  script:
    - sudo mv documents/docs/ /var/www/html/
  only:
    - master
